### ISSUE TITLE
Magda-combined-db cannot run migrations in local dev mode

### ISSUE THREAD

**Issue by ashleysommer** [TerriaJS/magda#449]
I'm not sure if this is a known limitation or not.
I couldn't see anything about it in the Getting Started doc, nor the Building and Running doc.

I believe this applies to the case of each database individually, as well as magda-combined-db, but I've only tried it on magda-combined-db so I can't be sure.

Running `npm run dev` under magda-combined-db cannot run migrations.
```
Database: jdbc:postgresql://localhost/auth (PostgreSQL 9.6)
Successfully validated 3 migrations (execution time 00:00.006s)
Creating Metadata table: "public"."schema_version"
Current version of schema "public": << Empty Schema >>
Migrating schema "public" to version 1 - Initial
Migrating schema "public" to version 1.1 - insert admin
Migrating schema "public" to version 1.2 - Create client user
ERROR:  syntax error at or near "WITH" at character 206
STATEMENT:  DO
        $body$
        BEGIN
            IF NOT EXISTS (
                SELECT                       -- SELECT list can stay empty for this
                FROM   pg_catalog.pg_user
                WHERE  usename = '') THEN
                    CREATE USER  WITH PASSWORD '';
           END IF;
        END
        $body$
ERROR: Migration of schema "public" to version 1.2 - Create client user failed! Changes successfully rolled back.
ERROR: 
Migration V1_2__Create_client_user.sql failed
---------------------------------------------
```
The ^above^ repeats 4 times, once for each of the 4 databases in combined-db.

It appears SQL template does not get populated with the `clientUserName` and `clientPassword` placeholder variables.
These are set by the psql cli tool invocation in magda-postgress migrate-and-start.sh file:
```
-placeholders.clientUserName="${CLIENT_USERNAME}" -placeholders.clientPassword="${CLIENT_PASSWORD}"
```
They are assigned empty strings because environment variables `CLIENT_USERNAME` and `CLIENT_PASSWORD` are not set when running the container locally.
That is because the dev config `/deploy/kubernetes/local/base/combined-db.yml` config file does not have CLIENT_USERNAME or CLIENT_PASSWORD set.

Those environment variables are only set in the `helm` _helpers.tpl template file, and only applied when running the container using helm.

Running 
```
env CLIENT_USERNAME=aaaa CLIENT_PASSWORD=xxxx npm run dev
```
Does not help, as those environment variables are not passed into the container.

**Comment by ashleysommer** [comment]
Workaround:
Modifying the `/deploy/kubernetes/local/base/combined-db.yml` file to include the `CLIENT_USERNAME` and `CLIENT_PASSWORD` environment variables in the container template spec fixes the problem for me:
```
    spec:
      containers:
      - name: combined-db
        image: localhost:5000/data61/magda-combined-db:latest
        env:
          - name: CLIENT_USERNAME
            value: "client"
          - name: CLIENT_PASSWORD
            value: "password"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      volumes:
      - name: data
        hostPath:
          path: /data/combinedDbData
```
However I don't know if that is the best solution.
